### ISSUE TITLE
Could not connect to your database to create an admin user

### ISSUE THREAD

**Issue by mosilver** [Theodo-UK/nestjs-admin#162]
According to the documentation I have installed package, added module admin, admin entity, the db migration that added adminuser table and then I try to add the admin user with command:

**$npx nestjs-admin createAdminUser**

and I get error:

Error: Could not connect to your database to create an admin user. Make sure you have an ormconfig file with a default connection or that your environment variables are set (see https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md).
    at Function.<anonymous> (C:\api\node_modules\nestjs-admin\bin\cliAdmin.module.ts:18:13)
    at Generator.throw (<anonymous>)
    at rejected (C:\api\node_modules\nestjs-admin\dist\bin\cliAdmin.module.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

but the  ormconfig works when I just start the app 
(after table remove as I get as well issue with: 
[ExceptionHandler] ER_TABLE_EXISTS_ERROR: Table 'adminuser' already exists +1ms
QueryFailedError: ER_TABLE_EXISTS_ERROR: Table 'adminuser' already exists )

**Comment by williamdclt** [comment]
Is it an `.ormconfig.ts` you pasted? It looks like TypeORM couldn't find it

It's not super clear from the docs, but basically the `nestjs-admin` command relies on TypeORM being able to discover your configuration automatically. Which means you have 2 options for it to work:

- have your config (`.ormconfig{.json, js, ts...}` or `.env`, [TypeORM docs here](https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md#using-environment-variables)) in your root folder (next to `package.json`)
- have the env vars [described here](https://github.com/typeorm/typeorm/blob/master/docs/using-ormconfig.md#using-environment-variables) exported in the shell executing `npx nestjs-admin` (TYPEORM_URL should be enough)

**Comment by mosilver** [comment]
I had the ormconfig.ts in src folder, so I moved it to the root of project near package.json but the effect is still the same - standard app is starting (left terminal) adding admin fails (right terminal), I attach the full content of config as well:

![error](https://user-images.githubusercontent.com/8830062/78883850-57636b00-7a5a-11ea-8af9-7d2d1a0a1187.jpg)
![localization](https://user-images.githubusercontent.com/8830062/78883852-58949800-7a5a-11ea-86be-25640f46d8e8.jpg)

[https://www.dropbox.com/s/u5kh259y3oa8uy7/localization.jpg?dl=0](url)
[https://www.dropbox.com/s/7njy07hvu9ag2w7/error.jpg?dl=0](url)
